### ISSUE TITLE
DLL load failed

### ISSUE THREAD

**Issue by Maxence-Leroy** [intel-isl/Open3D#979]
**Describe the bug**
I tried to install open3d-python on a new computer, it didn't work. The python install is cleaned. I also tried with Python 3.6.8, I have the same issue.

**To Reproduce**
1. pip install open3d-python
2. python -c "import open3d"

**Traceback**
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Python37\lib\site-packages\open3d\__init__.py", line 28, in <module>
    from .open3d import * # py2 py3 compatible
ImportError: DLL load failed: The specified module could not be found.

**Environment**
 - OS: Windows 10 build 17134 64 bits
 - Python version: 3.7.2 64 bits
 - Open3D version: 0.6.0.0
 - Is this remote workstation?: No
 - How did you install Open3D?: pip

**Comment by tansinjahan** [comment]
Is there any update on this? I am also facing the same issue while importing open3d-python. 
Traceback:
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Python3.5\lib\site-packages\open3d\__init__.py", line 13, in <module>
    from open3d.win32 import *
  File "C:\Python3.5\lib\site-packages\open3d\win32\__init__.py", line 11, in <module>
    globals().update(importlib.import_module('open3d.win32.64b.open3d').__dict__)
  File "C:\Python3.5\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "C:\Python3.5\lib\site-packages\open3d\win32\64b\__init__.py", line 7, in <module>
    globals().update(importlib.import_module('open3d.win32.64b.open3d').__dict__)
  File "C:\Python3.5\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ImportError: DLL load failed: The specified procedure could not be found.

Environment:
OS: Windows 10  64 bits
Python version: 3.5
Open3D version: 0.7.0.0
installed using pip.

**Comment by germanros1987** [comment]
We are looking into it. @yxlao

**Comment by iwaynee** [comment]
I just had the same problem but I've solved it by installing:
- microsoft visual c++ 2015 redistributable
- microsoft visual c++ 2013 redistributable
- microsoft visual c++ 2012 redistributable

don't know which it was, I just installed everyone. 
@germanros1987 Could you please add this as a dependencies?
Just a little hint would have saved me a lot of time...

**Comment by JianquanWang** [comment]
Hi all, the problem occurred when I use Python 3.8.0 on Win 10, and I have solved it by switching to Python 3.7.0. Considering this bug is caused by Python.

**Comment by protactinium91** [comment]
Hello is there a valid solution to this problem?
I am on Win10. I have microsoft visual c++ 2017 redistributable installed
and I have also downgraded Python to 3.6 but I still get the error

**Comment by kingaza** [comment]
me too

**To Reproduce**
Steps to reproduce the behavior:
```
    pip install open3d
    python -c "import open3d"
```


**Environment**
```
    OS: Windows 10 64 bits
    Python version: 3.7.3 64 bits
    Open3D version: 0.9.0.0
    Is this remote workstation?: No
    How did you install Open3D?: pip
```

**Comment by ivorycirrus** [comment]
@protactinium91 @kingaza I had a same problem and solved now.
I also had "ImportError: DLL load failed" error.
And then I installed "Microsoft Visual C++ Redistributable for Visual Studio 2015, 2017 and 2019".

My environments before,
Windows 10 64bit, Visual studio 2017, 
Python 3.7.5 (with Anaconda), Open3D 0.9.0.0 installed from pip

First, visit below. 
And install x86 and x64 packages in "Visual Studio 2015, 2017 and 2019" section.
https://support.microsoft.com/en-us/help/2977003/the-latest-supported-visual-c-downloads

After install packages, reboot windows. Then the Open3D runs normally.

**Comment by dfd19** [comment]
> @protactinium91 @kingaza I had a same problem and solved now.
> I also had "ImportError: DLL load failed" error.
> 
> My environments before,
> Windows 10 64bit, Visual studio 2017,
> Python 3.7.5 (with Anaconda), Open3D 0.9.0.0 installed from pip
> 
> And then I installed "Microsoft Visual C++ Redistributable for Visual Studio 2015, 2017 and 2019".
> 
> First, visit below.
> And install x86 and x64 packages in "Visual Studio 2015, 2017 and 2019" section.
> https://support.microsoft.com/en-us/help/2977003/the-latest-supported-visual-c-downloads
> 
> After install packages, reboot windows. Then the Open3D runs normally.

I have tried this, but still can't work at all. 
but somehow I have solved it with old version.

I also had "ImportError: DLL load failed" error. and I use conda environment. and also I use windows 10.

First, follow @ivorycirrus step (installing package). If you still had bug, continue to the next step

Second, i just create new environment conda with python 3.6
"conda create -n <NameEnV here> python=3.6"
and activate it
"conda activate <NameEnv>"

third. download packages library from here 
https://anaconda.org/open3d-admin/open3d/files?sort=ndownloads&sort_order=desc&version=0.6.0.0&type=conda
for my case, I download win64 py36.

fourth. install it with this command (makes sure that you are in your environment)
"conda install <namePackagesfromthe links>"

fifth. when I tried to run "import open3d", I got an error, because numpy hasn't installed yet. So I tried to install it with
"conda install numpy"

Then, somehow... it works.

(sorry for my broken English)

**Comment by elvetian** [comment]
> **Describe the bug**
> I tried to install open3d-python on a new computer, it didn't work. The python install is cleaned. I also tried with Python 3.6.8, I have the same issue.
> 
> **To Reproduce**
> Steps to reproduce the behavior:
> 
> 1. pip install open3d-python
> 2. python -c "import open3d"
> 
> **Traceback**
> Traceback (most recent call last):
> File "", line 1, in
> File "C:\Python37\lib\site-packages\open3d__init__.py", line 28, in
> from .open3d import * # py2 py3 compatible
> ImportError: DLL load failed: The specified module could not be found.
> 
> **Environment**
> 
> * OS: Windows 10 build 17134 64 bits
> * Python version: 3.7.2 64 bits
> * Open3D version: 0.6.0.0
> * Is this remote workstation?: No
> * How did you install Open3D?: pip

I resolved by deleting the "." before open3d:
from open3d import * # py2 py3 compatible

**Comment by PerspectivesLab** [comment]
got the same problem, impossible to solve, tried to remove the dot at "from open3d import * # py2 py3 compatible" but didnt resolve

**Comment by kitac3** [comment]
I had same problem

OS: Windows 10 
Python version: 3.7.6
Open3D version: 0.9.0.0

I resolved  by installed VC++ DLL x86,x64 both package.

x86: vc_redist.x86.exe
x64: vc_redist.x64.exe

if show dll load error yet
I recomend check dependency of   lib\site-packages\open3d\open3d.cp37-win_amd64.pyd
with Dependecies tool.

Dependencies
https://github.com/lucasg/Dependencies
https://github.com/lucasg/Dependencies/releases/download/v1.9/Dependencies_x64_Release.zip

**Comment by ohad-denh** [comment]
> I had same problem
> 
> OS: Windows 10
> Python version: 3.7.6
> Open3D version: 0.9.0.0
> 
> I resolved by installed VC++ DLL x86,x64 both package.
> 
> x86: vc_redist.x86.exe
> x64: vc_redist.x64.exe
> 
> if show dll load error yet
> I recomend check dependency of lib\site-packages\open3d\open3d.cp37-win_amd64.pyd
> with Dependecies tool.
> 
> Dependencies
> https://github.com/lucasg/Dependencies
> https://github.com/lucasg/Dependencies/releases/download/v1.9/Dependencies_x64_Release.zip

ty, worked for me

**Comment by izhangrui** [comment]
> > **Describe the bug**
> > I tried to install open3d-python on a new computer, it didn't work. The python install is cleaned. I also tried with Python 3.6.8, I have the same issue.
> > **To Reproduce**
> > Steps to reproduce the behavior:
> > 
> > 1. pip install open3d-python
> > 2. python -c "import open3d"
> > 
> > **Traceback**
> > Traceback (most recent call last):
> > File "", line 1, in
> > File "C:\Python37\lib\site-packages\open3d__init__.py", line 28, in
> > from .open3d import * # py2 py3 compatible
> > ImportError: DLL load failed: The specified module could not be found.
> > **Environment**
> > 
> > * OS: Windows 10 build 17134 64 bits
> > * Python version: 3.7.2 64 bits
> > * Open3D version: 0.6.0.0
> > * Is this remote workstation?: No
> > * How did you install Open3D?: pip
> 
> I resolved by deleting the "." before open3d:
> from open3d import * # py2 py3 compatible

thanks,it worked by  deleting the "."

**Comment by izhangrui** [comment]
> I had same problem
> 
> OS: Windows 10
> Python version: 3.7.6
> Open3D version: 0.9.0.0
> 
> I resolved by installed VC++ DLL x86,x64 both package.
> 
> x86: vc_redist.x86.exe
> x64: vc_redist.x64.exe
> 
> if show dll load error yet
> I recomend check dependency of lib\site-packages\open3d\open3d.cp37-win_amd64.pyd
> with Dependecies tool.
> 
> Dependencies
> https://github.com/lucasg/Dependencies
> https://github.com/lucasg/Dependencies/releases/download/v1.9/Dependencies_x64_Release.zip
![image](https://user-images.githubusercontent.com/25197453/75131835-9c804780-570f-11ea-8dd0-b3f650514238.png)
thanks,I download this dll,then it work

**Comment by yxlao** [comment]
I tested Open3D 0.9.0 pip and Conda installation under Windows 10 64-bit with python3.7 and they're all working for me.

Here's the full terminal recording for pip install:
https://terminalizer.com/view/fcc321e93273

Here's the full terminal recording for conda install:
https://terminalizer.com/view/0c3811b03274

Please try with the exact same command (including creating a fresh environment and activating it), and see if the problem still exists.

**Comment by syncle** [comment]
Please check [discussions in here](https://github.com/intel-isl/Open3D/issues/1487#issuecomment-592416175). In short, the reported issue is not reproducible with up-to-date python env and open3d package. Closing issue.

**Comment by Stubbleman** [comment]
> @protactinium91 @kingaza I had a same problem and solved now.
> I also had "ImportError: DLL load failed" error.
> 
> My environments before,
> Windows 10 64bit, Visual studio 2017,
> Python 3.7.5 (with Anaconda), Open3D 0.9.0.0 installed from pip
> 
> And then I installed "Microsoft Visual C++ Redistributable for Visual Studio 2015, 2017 and 2019".
> 
> First, visit below.
> And install x86 and x64 packages in "Visual Studio 2015, 2017 and 2019" section.
> https://support.microsoft.com/en-us/help/2977003/the-latest-supported-visual-c-downloads
> 
> After install packages, reboot windows. Then the Open3D runs normally.

This works for me, thanks!
